# Generated by Django 3.2.25 on 2024-12-15 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=30)),
                ('manufacturer', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=30)),
                ('interval', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_checked', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('link', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
